### ISSUE TITLE
Release for 1.7.2?

### ISSUE THREAD

**Issue by jussch** [javivelasco/react-css-themr#42]
I just recently updated a large chunk of my dependencies to fix some issues I was having. Once I updated however, react-css-themr started breaking my build. After some investigation, it appears the issue has already been fixed with [this commit](https://github.com/javivelasco/react-css-themr/commit/cb0501fe98317318ec4fa7272d66ab3926719455).

Wondering when react-css-themr is going to get the hotfix uploaded to npm, or if there is an alternate solution for dealing with the undefined `mixinValue` variable.

Thanks

**Comment by javivelasco** [comment]
Done! Sorry for taking this long

**Comment by jussch** [comment]
Thanks a bunch!
