### ISSUE TITLE
themeable() merging issues

### ISSUE THREAD

**Issue by powah** [javivelasco/react-css-themr#52]
In the nested theme case shown below:
```
const themeA = {};
const themeB = {
    nested: {
        bar: 'bar'
    }
};
themeable(themeA, themeB);
```
we get an error: 
_Uncaught Error: You are merging a string "" with an Object,Make sure you are passing the proper theme descriptors._

**Comment by raveclassic** [comment]
@powah I belive I fixed it under #47 but it wasn't released, only merged. Try to checkout current master.

**Comment by raveclassic** [comment]
@javivelasco Could you please release current master as `2.1.0`?

**Comment by javivelasco** [comment]
Releasing today!
