### ISSUE TITLE
Uncaught TypeError: this.props.mapThemrProps is not a function

### ISSUE THREAD

**Issue by alexeyMohnatkin** [javivelasco/react-css-themr#61]

**Comment by raveclassic** [comment]
Something went wrong... :)

**Comment by raveclassic** [comment]
@alexeyMohnatkin Could you please provide a minimal representation gist/repo? I cannot reproduce the error.

**Comment by javivelasco** [comment]
That's weird. All test are passing and there is a default value set up, it shouldn't fail unless you give an option that is not a function there. @alexeyMohnatkin please give us an example! :)

**Comment by alexeyMohnatkin** [comment]
I need time to make example. I didin't pass any new props. I've just updated react-css-themr and got this error.

**Comment by alexeyMohnatkin** [comment]
It happens when I define defaultProps for decorated component. https://www.webpackbin.com/bins/-Kk0TTaHGCq00TebCuG1

**Comment by raveclassic** [comment]
@alexeyMohnatkin This happens because you override static _after_ decorating the class. Just add them as static properties:
```javascript
@themr(Symbol())
class Foo {
  static defaultProps = {};
  static propTypes = {};
}
```

Or extend them instead of overwriting:
```javascript
Foo.defaultProps = {
  ...Foo.defaultProps
};
```

**Comment by alexeyMohnatkin** [comment]
I've already found solution, thank you

**Comment by huchenme** [comment]
I think the error message is not helpful. I have accidentally put `defaultProps` for one of the components using `react-css-themr` and got this error message "Uncaught TypeError: this.props.mapThemrProps is not a function" where no one has any clue where to find the root cause. 

The expected behavior will be no runtime error if someone overrides the `defaultProps` in another component.

**Comment by idangozlan** [comment]
@alexeyMohnatkin  what is the solution that you found?

**Comment by alexeyMohnatkin** [comment]
@idangozlan it's described here https://github.com/javivelasco/react-css-themr/issues/61#issuecomment-301258266
