### ISSUE TITLE
Default theming example

### ISSUE THREAD

**Issue by xli1000** [javivelasco/react-css-themr#70]
The `README.md` shows this example where a theme is passed in as a prop to override the default theme:

```js
import style from './Section.css';
[...]
<SuccessButton theme={style.button}>Yai!</SuccessButton>
```

But this didn't work for me--since `style` is an object like `{ button: 'button-1jq92' }`, `style.button` is a string and can't be used to override the default theme.

I had to do something like this: 
```js
<SuccessButton theme={ {button: style.button} }>Yai!</SuccessButton>
```
or just `theme={style}`.

Am I missing something, or is this a mistake in that example?

**Comment by raveclassic** [comment]
You are correct, it's a mistake in the docs. `theme` prop always accepts an object. 
Related: #31

**Comment by xli1000** [comment]
I see that a PR has already been submitted to correct this: [#69](https://github.com/javivelasco/react-css-themr/pull/69).
