### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by MrHavard** [javivelasco/react-css-themr#87]
I've noticed that quite a few issues out here have not been commented on by the maintainer and there are 8 pull requests that have been sitting waiting 6 months or more. Is there a more active fork or is there another alternative to react-css-themr that is better or more frequently updated. 

For the record themr works well for me in how I'm using it today. But I worry with how quickly the market moves that it may become incompatible with some future release of React. I want to make sure I'm planning ahead.

**Comment by klimashkin** [comment]
A new [@css-modules-theme/react](https://github.com/klimashkin/css-modules-theme) module has been created, which solves css-modules composition in different, more performant and cacheable way, that also doesn't require any hoc or forwardRef wrappers.
Feel free to try it out and post a feedback there
